 
name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ec2-user/git_repo/AWS-EC2-and-GitHub/
            git pull
            sudo cp index.html /var/www/html/index.html
            sudo cp VPV00111.jpg /var/www/html/VPV00111.jpg
            Sudo cp Screenshot.png /var/www/html/Screenshot.png
